[package]
name = "siri-lite"
version = "0.1.0"
authors = ["antoine-de <antoine.desbordes@gmail.com>"]
edition = "2021"

[dependencies]

serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
